export const videosData = [
    {
      "id": 1,
      "title": "90 Day Full Stack Developer Roadmap 2024",
      "description": "Being a full stack developer means you possess a comprehensive skill set that spans both front-end and back-end technologies.",
      "url": "https://www.youtube.com/embed/og4p1qJNf1Y",
      "thumbnail": "https://via.placeholder.com/150",
      "category": "Education",
      "duration": "55:48",
      "uploadDate": "2023-12-24",
      "views": 147783,
      "likes": 5400,
      "dislikes": 15
    },
    {
      "id": 2,
      "title": "Dragon Ball Sigma moments in Hindi",
      "description": "Dragon Ball Sigma moments in Hindi | Dragon Ball Funny moments in Hindi",
      "url": "https://www.youtube.com/embed/O3HKJcrtuhQ",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Anime",
      "duration": "11:38",
      "uploadDate": "2024-10-19",
      "views": 37000,
      "likes": 673,
      "dislikes": 3
    },
    {
      "id": 3,
      "title": "A Doctor Behind Bars",
      "description": "A Doctor Behind Bars: Became Hero by Saving Lives Against All Odds",
      "url": "https://www.youtube.com/embed/HOCo2MqA9hk",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Story",
      "duration": "34:53",
      "uploadDate": "2024-11-29",
      "views": 340000,
      "likes": 5600,
      "dislikes": 190
    },
    {
      "id": 4,
      "title": "Iss JAADUI Car se Dushmani padegi Mehngi",
      "description": "Master CSS Grid and build complex layouts with ease.",
      "url": "https://www.youtube.com/embed/kjU8QfExDfw",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Story",
      "duration": "18:09",
      "uploadDate": "2024-12-03",
      "views": 1000000,
      "likes": 1000,
      "dislikes": 200
    },
    {
      "id": 5,
      "title": "Create Mobile Games Using ChatGPT Without Coding Skills ",
      "description": "Create Mobile Games Using ChatGPT Without Coding Skills - Easy Guide",
      "url": "https://www.youtube.com/embed/vwfYAjgZPrA",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Earning",
      "duration": "09:44",
      "uploadDate": "2024-12-12",
      "views": 5200,
      "likes": 395,
      "dislikes": 0
    },
    {
      "id": 6,
      "title": "Python for Data Science",
      "description": "Get started with Python programming for data science.",
      "url": "https://www.youtube.com/embed/7DSpYPja9qM?si=860y9yD3lkScpU5o",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Education",
      "duration": "3:00:00",
      "uploadDate": "2024-06-15",
      "views": 940000,
      "likes": 11000,
      "dislikes": 320
    },
    {
      "id": 7,
      "title": "Netwokring For Ethical Hacking",
      "description": "Netwokring For  Ethical Hacking | Networking Full Course For Beginners 2024 with notes",
      "url": "https://www.youtube.com/embed/LQ0Il-vuSiQ",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Education",
      "duration": "2:58:06",
      "uploadDate": "2024-07-05",
      "views": 1000,
      "likes": 61,
      "dislikes": 0
    },
    {
      "id": 8,
      "title": "Create a Game Without Coding Earn Money Online Easily!",
      "description": "Create a Game Without Coding Using ChatGPT & Earn Money Online Easily!",
      "url": "https://www.youtube.com/embed/IqsUkE84To8",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Technology",
      "duration": "1:50:00",
      "uploadDate": "2024-08-10",
      "views": 39000,
      "likes": 7500,
      "dislikes": 250
    },
    {
      "id": 9,
      "title": "CSS Tutorial In Hindi",
      "description": "CSS Tutorial For Beginners in Hindi: In this CSS3 tutorial in Hindi we will learn everything you need to learn about CSS from scratch.",
      "url": "https://www.youtube.com/embed/Edsxf_NBFrw",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Health & Fitness",
      "duration": "08:21:00",
      "uploadDate": "2021-04-25",
      "views": 6736299,
      "likes": 133253,
      "dislikes": 400
    },
    {
      "id": 10,
      "title": "7 Levels to Access DARK WEB safely",
      "description": "we break down the 7 Levels of Security you need to know before venturing into the hidden depths of the internet. From using the Tor browser to advanced methods like VPNs, Tails OS, and Whonix, we guide you through the best practices for browsing safely and anonymously.",
      "url": "https://www.youtube.com/embed/F7WlfLe9br8",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Education",
      "duration": "0:39:16",
      "uploadDate": "2024-12-07",
      "views": 5674,
      "likes": 228,
      "dislikes": 0
    },
    {
      "id": 11,
      "title": "The History of Artificial Intelligence AI",
      "description": "A deep dive into the history and future of AI.",
      "url": "https://www.youtube.com/embed/fBncbUmO-L4?si=pl7q_1XDPDaBEWpE",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Technology",
      "duration": "2:00:00",
      "uploadDate": "2024-10-01",
      "views": 770000,
      "likes": 8900,
      "dislikes": 400
    },
    {
      "id": 12,
      "title": "Yamoshi Travels To The Past And Meets Akumo",
      "description": "MUNDO DRAGON BALL © - DRAGON BALL WORLD.",
      "url": "https://www.youtube.com/embed/gxycym75RBE",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Anime",
      "duration": "48:23",
      "uploadDate": "2024-11-23",
      "views": 187367,
      "likes": 4820,
      "dislikes": 150
    },
    {
      "id": 13,
      "title": "Cybersecurity Complete RoadMap",
      "description": "Cybersecurity Complete RoadMap for 2025 (From Basics to Advanced).",
      "url": "https://www.youtube.com/embed/ocDmB0muCC4",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Technology",
      "duration": "21:43",
      "uploadDate": "2024-12-09",
      "views": 20872,
      "likes": 1000,
      "dislikes": 10
    },
    {
      "id": 14,
      "title": "How AI Killed the Internet",
      "description": "How AI Killed the Internet",
      "url": "https://www.youtube.com/embed/Tj_RphBpwiw",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Education",
      "duration": "12:19",
      "uploadDate": "2024-12-08",
      "views": 483535,
      "likes": 50000,
      "dislikes": 100
    },
    {
      "id": 15,
      "title": "#1 Excel trick to earn Rs 1300 in just 1 hour 2024",
      "description": "#1 Excel trick to earn Rs 1300 in just 1 hour 2024.",
      "url": "https://www.youtube.com/embed/Oo9fXTuz2iQ",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Earning",
      "duration": "17:27",
      "uploadDate": "2024-02-13",
      "views": 1786479,
      "likes": 10700,
      "dislikes": 120
    },
    {
      "id": 16,
      "title": "Coding Interview Questions - JavaScript",
      "description": "Tackle some common JavaScript interview questions in this tutorial.",
      "url": "https://www.youtube.com/embed/zmk32_QA71s?si=lhjFkTLw7gmh54XJ",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Technology",
      "duration": "1:30:00",
      "uploadDate": "2024-05-15",
      "views": 430000,
      "likes": 5000,
      "dislikes": 190
    },
    {
      "id": 17,
      "title": "Bhojpuri reels videos 2024",
      "description": "Bhojpuri reels videos 2024.",
      "url": "https://www.youtube.com/embed/xPRbxdLCSIo",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Music",
      "duration": "22:16",
      "uploadDate": "2024-10-05",
      "views": 72792,
      "likes": 496,
      "dislikes": 90
    },
    {
      "id": 18,
      "title": "I Let AI Hack for Me",
      "description": "In this video, I take on the Basic Pentesting Room on TryHackMe using the power of WhiteRabbitNeo AI",
      "url": "https://www.youtube.com/embed/mD6hh8gnvGA",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Technology",
      "duration": "29:20",
      "uploadDate": "2024-11-14",
      "views": 41559,
      "likes": 1900,
      "dislikes": 3
    },
    {
      "id": 19,
      "title": "DevOps Complete Guide for 2025",
      "description": "DevOps Complete Guide for 2025",
      "url": "https://www.youtube.com/embed/RRBF2YWXFtY",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Education",
      "duration": "18:09",
      "uploadDate": "2024-12-10",
      "views": 88129,
      "likes": 4800,
      "dislikes": 70
    },
    {
      "id": 20,
      "title": "React Tutorial in Hindi 🔥🔥",
      "description": "ReactJs Complete Course: In this complete react tutorial for beginners in Hindi",
      "url": "https://www.youtube.com/embed/RGKi6LSPDLU",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Technology",
      "duration": "2:00:00",
      "uploadDate": "2021-04-14",
      "views": 2957335,
      "likes": 66000,
      "dislikes": 210
    },
    {
      "id": 21,
      "title": "How to Build a Mobile App with React Native",
      "description": "Step-by-step guide to building a mobile app using React Native.",
      "url": "https://www.youtube.com/embed/gvkqT_Uoahw?si=Eew7VOf5XXzEoO2t",
      "thumbnail": "https://via.placeholder.com/190",
      "category": "Technology",
      "duration": "2:15:00",
      "uploadDate": "2024-08-25",
      "views": 520000,
      "likes": 6800,
      "dislikes": 210
    },
]